version: '3.8'

services:
      
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
    volumes:
       - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - my_etl_network

networks:
  my_etl_network:
    driver: bridge

volumes:
  postgres-data: